.PHONY: all mypy flake8 tests

all: mypy flake8 tests

#------------------------------------------------------------------------------
# Python mypy, flake8 and unittests
#------------------------------------------------------------------------------

mypy:
	mypy --strict \
		src tests utils

tests:
	python3 -m unittest

# Run flake8 on the src/acetime/zonedb files separately because those are
# code-generated by a script, and it's very difficult to get the formatting
# right to make flake8 happy.
#
# Sweep 1:
# * W503 and W504 are both enabled by default and are mutual contradictory, so
# we have to suppress one of them.
# * E501 uses 79 columns by default, but 80 is the default line wrap in vim, so
# change the line-length.
#
# Sweep 2:
# * F403,F405 complains about 'import *' which is used because there are so
# many imports for these generated files.
# * E303 warns about too many blank lines, which is really hard to get right in
# a code generator.
# * W391 complains about blank lines at the end of the file, which is caused by
# the same reasons as E303
# * Set the maximum line to 100 because it's hard to wrap with a code
# generator.
flake8:
	flake8 . \
		--exclude src/acetime/zonedb \
		--ignore W503 \
		--max-line-length=80 \
		--show-source \
		--statistics
	flake8 src/acetime/zonedb \
		--ignore W503,F403,F405,E303,W391 \
		--max-line-length=100 \
		--show-source \
		--statistics

zonedbs:
	make -C src/acetime/zonedb/
